-- 0004 — events.seq: a monotonic append-order key (ADR-0004, ADR-0012).
--
-- `ts` defaults to now(), which in Postgres is the *transaction* start time, so
-- multiple events appended within one transaction share an identical timestamp
-- and their read-back order under `ORDER BY ts` is non-deterministic. An
-- append-only log must replay in true insertion order, so we add a gapless,
-- strictly-increasing identity column and order reads by it. `ts` is retained
-- for time-window filtering and telemetry; `seq` is the canonical order.
--
-- Forward-only and idempotent: ADD COLUMN IF NOT EXISTS is a no-op if the column
-- already exists (and the migration runner skips already-applied files anyway).
-- Note: attaching a GENERATED identity to a table with pre-existing rows assigns
-- them seq values in physical-scan order; this is only exact for rows inserted
-- after the column exists, which is all that append-order correctness requires.

ALTER TABLE events
    ADD COLUMN IF NOT EXISTS seq bigint GENERATED BY DEFAULT AS IDENTITY;

-- Replay a single task's / a workstream's timeline in true append order.
CREATE INDEX IF NOT EXISTS events_task_seq_idx ON events (task_id, seq);
CREATE INDEX IF NOT EXISTS events_workstream_seq_idx ON events (workstream, seq);
