-- 0015 — decisions: the async open-ended stakeholder-DECISION store
-- (ADR-0025, extends ADR-0006/0015; the open-ended analogue of approvals/0007).
--
-- A binary 🔴 approval (0007) is approve/deny. An OPEN-ENDED decision is a real
-- question the stakeholder must answer — a chosen option or free text (e.g. "which
-- vendor?", "what tone for the launch post?"). Because the stakeholder is not
-- monitoring 24/7 (ADR-0006: batched, async, human < 4hrs/day), a decision must
-- NOT block the worker: raising one PARKS the dependent task (`blocked`) so the
-- worker grabs other work, and answering it RESUMES the task (`blocked →
-- up_for_grabs`) so a fresh worker re-grabs it and reads the answer.
--
-- The QUESTION and ANSWER text live in this row only; the event log carries just
-- ids/status/seq/has_options/resolver (body-free — CLAUDE.md invariants 5 & 6),
-- mirroring the approvals/trajectory discipline.
--
-- Forward-only and idempotent (like 0007/0014): CREATE ... IF NOT EXISTS is a
-- no-op on re-run and the migration runner skips already-applied files anyway.

CREATE TABLE IF NOT EXISTS decisions (
    id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    workstream         text NOT NULL,
    question           text NOT NULL,                 -- the open-ended question (body; not on the wire)
    options            jsonb,                         -- list of choices; NULL ⇒ free-text answer allowed
    status             text NOT NULL DEFAULT 'open'
                         CHECK (status IN ('open', 'answered', 'withdrawn')),
    answer             text,                          -- the chosen option / free text (body; not on the wire)
    answered_by        text,                          -- who answered (human/spokesman id)
    dependent_task_id  uuid REFERENCES tasks (id),    -- the parked task to resume on answer
    default_choice     text,                          -- the safe default to note if unanswered
    seq                bigint GENERATED BY DEFAULT AS IDENTITY,  -- monotonic append order
    created_at         timestamptz NOT NULL DEFAULT now(),
    answered_at        timestamptz                    -- set when answered
);

-- Digest/queue path: list currently-open decisions for the Spokesman.
CREATE INDEX IF NOT EXISTS decisions_status_idx ON decisions (status);
-- Per-workstream scoping (open_decisions(workstream=...)).
CREATE INDEX IF NOT EXISTS decisions_workstream_idx ON decisions (workstream);
