-- 0018 — Spokesman per-session conversation memory (ADR-0026, extends 0017).
--
-- The Spokesman was AMNESIAC across turns: every inbound message rebuilt the
-- model prompt as [system, current_text] with no prior-turn history, so turn 2
-- ("what's my name?") could not see turn 1 ("my name is Jerry"). This table is
-- the ONE place a dialogue BODY lives — bounded, per-session conversation
-- history the converse loop threads into the prompt.
--
-- INVARIANT 6 (body-free event log): the turn `content` (what the human said /
-- what Spokesman replied) lives in THIS DB row ONLY — never in an event payload,
-- exactly as `spokesman_prep_cache` / `decisions.answer` keep bodies DB-local.
-- The event log still carries just char counts (EVENT_HUMAN_MESSAGE), never text.
--
-- `seq` follows the events/decisions idiom (0004/0015): a strictly-increasing
-- INSERT-order key so a session's turns read back in a stable, deterministic
-- order (a plain `ORDER BY created_at` is non-deterministic within a txn since
-- now() is the transaction start time). See 0004 for the honest seq guarantee.
--
-- Forward-only and idempotent: CREATE ... IF NOT EXISTS is a no-op on re-run and
-- the migration runner skips already-applied files anyway.

CREATE TABLE IF NOT EXISTS spokesman_conversations (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    session_key  text NOT NULL,                          -- SMS sender id / web session uuid
    role         text NOT NULL
                   CHECK (role IN ('human', 'spokesman')),
    content      text NOT NULL,                          -- the turn body — DB-LOCAL ONLY, never on the wire
    seq          bigint GENERATED BY DEFAULT AS IDENTITY, -- monotonic append order (see 0004)
    workstream   text,
    created_at   timestamptz NOT NULL DEFAULT now()
);

-- Load a single session's history in true append order (recent_turns()).
CREATE INDEX IF NOT EXISTS spokesman_conversations_session_seq_idx
    ON spokesman_conversations (session_key, seq);
