#!/usr/bin/env bash
# AI Studio — cold-start onboarding.
# Collects API keys / credentials / personal config and writes them to a
# git-ignored local file (.env by default). NEVER writes secrets into tracked
# files, and never echoes secret values back. Safe to re-run; existing values are
# preserved unless you overwrite them. See docs/onboarding.md and ADR-0011.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${AI_STUDIO_SECRETS:-$REPO_ROOT/.env}"
EXAMPLE="$REPO_ROOT/.env.example"

# Refuse to write secrets into a git-tracked path.
if git -C "$REPO_ROOT" ls-files --error-unmatch "$ENV_FILE" >/dev/null 2>&1; then
  echo "REFUSING: $ENV_FILE is tracked by git. Point AI_STUDIO_SECRETS elsewhere." >&2
  exit 1
fi

echo "AI Studio onboarding → writing to: $ENV_FILE"
echo "(Press Enter to keep an existing value. Leave blank to skip what you lack.)"
echo

# Load existing values (so re-runs preserve them). The file is trusted local input.
declare -A VAL
if [[ -f "$ENV_FILE" ]]; then
  # shellcheck disable=SC1090
  set -a; source "$ENV_FILE" 2>/dev/null || true; set +a
fi

# masked display of a possibly-set secret
mask() { local v="$1"; [[ -z "$v" ]] && { echo "(unset)"; return; }; echo "****${v: -4}"; }

# prompt_var NAME "description" mode   (mode: plain | secret | genpass)
prompt_var() {
  local name="$1" desc="$2" mode="${3:-plain}" cur="${!1:-}" input=""
  case "$mode" in
    secret)
      printf '%s\n  current: %s\n  new value (hidden, Enter=keep): ' "$desc" "$(mask "$cur")"
      read -rs input; echo ;;
    genpass)
      if [[ -z "$cur" ]]; then
        cur="$(openssl rand -hex 24)"
        printf '%s\n  generated a random value.\n' "$desc"
      else
        printf '%s\n  current: %s (Enter=keep)\n' "$desc" "$(mask "$cur")"
      fi ;;
    *)
      printf '%s\n  current: [%s]\n  new value (Enter=keep): ' "$desc" "$cur"
      read -r input ;;
  esac
  VAL["$name"]="${input:-$cur}"
  echo
}

echo "== Model provider keys =="
prompt_var ANTHROPIC_API_KEY   "Anthropic (Claude) API key"        secret
prompt_var OPENAI_API_KEY      "OpenAI API key"                    secret
prompt_var GOOGLE_API_KEY      "Google (Gemini) API key"           secret
prompt_var VOYAGE_API_KEY      "Voyage embeddings API key"         secret
prompt_var EMBEDDINGS_PROVIDER "Embeddings provider (google|openai|voyage)" plain
# Cursor is an executor SUBSTRATE + a guarded router adapter, not a keyed HTTP
# provider: inference runs only via its agent-harness CLI (`cursor-agent -p ...`).
# This key authenticates that CLI (coding worker + the cursor-cli router adapter).
prompt_var CURSOR_API_KEY      "Cursor API key (agent-harness CLI; optional)" secret
# Optional: swap the sandboxed coding worker CLI (default: opencode). Set to
# `cursor-agent` to use Cursor as the coding worker. Non-secret config.
prompt_var CODING_WORKER_CMD   "Coding worker CLI (opencode|cursor-agent; optional)" plain

echo "== Stakeholder WhatsApp (Meta Cloud API) =="
prompt_var WHATSAPP_PHONE_NUMBER_ID      "WhatsApp phone number ID"          plain
prompt_var WHATSAPP_BUSINESS_ACCOUNT_ID  "WhatsApp business account ID"      plain
prompt_var WHATSAPP_ACCESS_TOKEN         "WhatsApp permanent access token"   secret
prompt_var WHATSAPP_APP_SECRET           "WhatsApp app secret"               secret
prompt_var WHATSAPP_VERIFY_TOKEN         "Webhook verify token (you choose)" secret
prompt_var STAKEHOLDER_WHATSAPP_NUMBER   "Your WhatsApp number (LOCAL ONLY)" plain

prompt_var SPOKESMAN_API_TOKEN "Spokesman control-plane token (gates /notify + /digest/flush)" genpass

echo "== Public webhook tunnel =="
prompt_var TUNNEL_PROVIDER          "Tunnel provider (cloudflared|tailscale|ngrok)" plain
prompt_var CLOUDFLARED_TUNNEL_TOKEN "Cloudflared tunnel token"                      secret

echo "== Local infra credentials (auto-generated if blank) =="
prompt_var POSTGRES_PASSWORD  "Postgres password"  genpass
prompt_var MINIO_ROOT_USER    "MinIO root user"    plain
prompt_var MINIO_ROOT_PASSWORD "MinIO root password" genpass
prompt_var GRAFANA_ADMIN_PASSWORD "Grafana admin password" genpass

VAL[AI_STUDIO_ENV]="${AI_STUDIO_ENV:-dev}"
VAL[MINIO_ROOT_USER]="${VAL[MINIO_ROOT_USER]:-aistudio}"

# Write atomically with tight permissions.
TMP="$(mktemp)"
{
  echo "# AI Studio secrets — generated by scripts/onboarding.sh. DO NOT COMMIT."
  echo "# $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  for k in AI_STUDIO_ENV \
           ANTHROPIC_API_KEY OPENAI_API_KEY GOOGLE_API_KEY VOYAGE_API_KEY EMBEDDINGS_PROVIDER \
           CURSOR_API_KEY CODING_WORKER_CMD \
           WHATSAPP_PHONE_NUMBER_ID WHATSAPP_BUSINESS_ACCOUNT_ID WHATSAPP_ACCESS_TOKEN \
           WHATSAPP_APP_SECRET WHATSAPP_VERIFY_TOKEN STAKEHOLDER_WHATSAPP_NUMBER \
           SPOKESMAN_API_TOKEN \
           TUNNEL_PROVIDER CLOUDFLARED_TUNNEL_TOKEN \
           POSTGRES_PASSWORD MINIO_ROOT_USER MINIO_ROOT_PASSWORD GRAFANA_ADMIN_PASSWORD; do
    printf '%s=%s\n' "$k" "${VAL[$k]:-}"
  done
} > "$TMP"
chmod 600 "$TMP"
mv "$TMP" "$ENV_FILE"

echo "Wrote $ENV_FILE (chmod 600). It is git-ignored — verify with: git check-ignore .env"
echo "Done. Re-run anytime to add or rotate values."
echo
echo "Note: this onboarding runs fine in Cursor's local integrated terminal (it"
echo "  just writes your local .env). Cursor *cloud* agents do NOT read this file —"
echo "  inject CURSOR_API_KEY (and any other secret) via their Secrets UI instead;"
echo "  never bake secrets into tracked files or agent config (ADR-0011)."
